image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - test

build-code:
  stage: test
  script:
    - rustup target add riscv64gc-unknown-none-elf
    - cargo build

lint-code:
  stage: test
  script:
    - rustup target add riscv64gc-unknown-none-elf
    - rustup component add clippy
    - cargo clippy -- -D warnings

format-code:
  stage: test
  script:
    - rustup target add riscv64gc-unknown-none-elf
    - rustup component add rustfmt
    - cargo fmt -- --check
