[package]
name = "salus"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
strip = "debuginfo"
codegen-units = 1
panic = "abort"

[[bin]]
name = "salus"
path = "src/main.rs"

[[bin]]
name = "tellus"
path = "src/tellus.rs"

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
device_tree = { path = "./device-tree" }
hyp_alloc = { path = "./hyp-alloc" }
memoffset = { version = ">=0.6.5", features = ["unstable_const"] }
once_cell = { version = "1.10", default-features = false }
page_collections = { path = "./page-collections" }
riscv_page_tables = { path = "./riscv-page-tables" }
riscv_pages = { path = "./riscv-pages" }
riscv_regs = { path = "./riscv-regs" }
sbi = { path = "./sbi" }
sha2 = {version = "0.10", default-features = false }
spin = { version = "*", default-features = false }

[workspace]
